### ISSUE TITLE
exposed secrets

### ISSUE THREAD

**Issue by SubhrajitPrusty** [anoob09/HerokuSputifyServer#1]
https://github.com/anoob09/HerokuSputifyServer/blob/a97c6c4c65518a0064daec1b414f8171dc5c492d/app.py#L11

use heroku config to declare secrets

**Comment by anoob09** [comment]
Thanks for pointing out. More suggestions?

**Comment by SubhrajitPrusty** [comment]
Your pycache folder should not be here
